CREATE TABLE country (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   country_name varchar(255) not null,
   country_code varchar(20) not null,
   nationality varchar(255) not null
);


create sequence country_sequence start with 5 increment by 1;


insert into country (country_name, country_code, nationality) values ('Lithuania', 'LT', 'Lithuanian');
insert into country (country_name, country_code, nationality) values ('Latvia', 'LV', 'Latvian');
insert into country (country_name, country_code, nationality) values ('Estonia', 'EE', 'Estonian');
insert into country (country_name, country_code, nationality) values ('Sweden', 'SE', 'Swedish');




